version: '3'

services:
  mailserver:
    build:
      context: ..
      dockerfile: /root/mailserver/Dockerfile
    container_name: mailserver
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    environment:
      - DOMAIN=fernandosalom.es
      - EMAIL=hola@fernandosalom.es
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/mail:/var/log/mail
    restart: unless-stopped
