# Generated by Django 5.1.1 on 2024-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedbo',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='notificationdbo',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationdbo',
            options={'verbose_name': 'Notificación a usuario', 'verbose_name_plural': 'Notificaciones a usuarios'},
        ),
        migrations.AlterField(
            model_name='notificationdbo',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
