/var/log/fail2ban.log {
    daily                 # Rotar los logs diariamente
    rotate 7              # Mantener 7 días de logs antes de eliminarlos
    size 100M             # Rotar cuando el archivo alcance los 100 MB
    compress              # Comprimir archivos rotados
    delaycompress         # Retrasar la compresión hasta la siguiente rotación
    missingok             # Ignorar si el archivo no existe
    notifempty            # No rotar archivos vacíos
    create 640 root adm   # Crear archivos de log con permisos específicos
    postrotate
        fail2ban-client flushlogs > /dev/null 2>&1 || true
    endscript
}
