name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Start ssh-agent
      id: start-ssh-agent
      run: eval $(ssh-agent -s)

    - name: Add SSH key
      run: |
        echo "${{ secrets.DROPLET_SSH_KEY }}" | tr -d '\r' > key.pem
        chmod 600 key.pem
        ssh-add key.pem
      env:
        SSH_PASSPHRASE: ""

    - name: Create project directory on server if not exists
      run: ssh -o StrictHostKeyChecking=no -i key.pem
